#! /usr/bin/env zsh

# flickloop — run flickpapr forever in a sleep loop
#
# called by flickd

sleeptime=${FLICK_INTVL=10m}

print "Refresh interval set to: $sleeptime"

while `true`; do
  flickpapr
  sleep $sleeptime
done
